USE [master]
GO

/****** Object:  Database [DIANA]    Script Date: 1/9/2023 2:27:27 PM ******/
CREATE DATABASE [DIANA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DIANA', FILENAME = N'D:\DATA\DIANA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [IMG] 
( NAME = N'DIANA_img', FILENAME = N'D:\DATA\DIANA_img.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DIANA_log', FILENAME = N'D:\DATA\DIANA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DIANA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DIANA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DIANA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DIANA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DIANA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DIANA] SET ARITHABORT OFF 
GO

ALTER DATABASE [DIANA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DIANA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DIANA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DIANA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DIANA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DIANA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DIANA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DIANA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DIANA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DIANA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DIANA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DIANA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DIANA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DIANA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DIANA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DIANA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DIANA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DIANA] SET RECOVERY FULL 
GO

ALTER DATABASE [DIANA] SET  MULTI_USER 
GO

ALTER DATABASE [DIANA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DIANA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DIANA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DIANA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DIANA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DIANA] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DIANA] SET  READ_WRITE 
GO





USE [DIANA];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[ZTA500] (
--[Id] bigint IDENTITY(1, 1) NOT NULL,
[Id] bigint NOT NULL,
[Sys_cd] varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
[Sql_id] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Sql_txt] varchar(MAX) COLLATE Korean_Wansung_CI_AS NULL,
[Memo] varchar(254) COLLATE Korean_Wansung_CI_AS NULL,
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH ( PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE )
 ON [PRIMARY]
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY];
GO
ALTER TABLE [dbo].[ZTA500] SET (LOCK_ESCALATION = TABLE);
GO

INSERT INTO APIUAT01.DIANA.dbo.ZTA500    SELECT * FROM ACE.dbo.ZTA500



USE [DIANA];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[ZTA400] (
[Sys_cd] varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL,
[Frm_id] varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
[Wkset_id] varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
[CRUD] char(1) COLLATE Korean_Wansung_CI_AS NOT NULL,
[Sql_txt] varchar(MAX) COLLATE Korean_Wansung_CI_AS NULL,
[Memo] varchar(MAX) COLLATE Korean_Wansung_CI_AS NULL,
PRIMARY KEY CLUSTERED ([Sys_cd] ASC, [Frm_id] ASC, [Wkset_id] ASC, [CRUD] ASC)
WITH ( PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE )
 ON [PRIMARY]
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY];
GO
ALTER TABLE [dbo].[ZTA400] SET (LOCK_ESCALATION = TABLE);
GO

select * into APIUAT01.DIANA.dbo.ZTA400 from ZTA400
INSERT INTO APIUAT01.DIANA.dbo.ZTA400    SELECT * FROM ACE.dbo.ZTA400


USE [DIANA];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[ZTA31Ref] (
--[Id] bigint IDENTITY(1, 1) NOT NULL,
[Id] bigint NOT NULL,
[Sys_cd] varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
[Frm_id] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Wkset_id] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Ctrl_id] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Param_wkset] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Param_name] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Param_value] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Pid] bigint NULL,
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH ( PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE )
 ON [PRIMARY]
)
ON [PRIMARY];
GO
ALTER TABLE [dbo].[ZTA31Ref] SET (LOCK_ESCALATION = TABLE);
GO

select * into APIUAT01.DIANA.dbo.ZTA31Ref from ZTA31Ref
INSERT INTO APIUAT01.DIANA.dbo.ZTA31Ref  SELECT * FROM ACE.dbo.ZTA31Ref


USE [DIANA];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[ZTA31Push] (
--[Id] bigint IDENTITY(1, 1) NOT NULL,
[Id] bigint NOT NULL,
[Sys_cd] varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
[Frm_id] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Wkset_id] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Ctrl_id] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Param_wkset] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Param_name] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Param_value] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Pid] bigint NULL,
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH ( PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE )
 ON [PRIMARY]
)
ON [PRIMARY];
GO
ALTER TABLE [dbo].[ZTA31Push] SET (LOCK_ESCALATION = TABLE);
GO

select * into APIUAT01.DIANA.dbo.ZTA31Push from ZTA31Push
INSERT INTO APIUAT01.DIANA.dbo.ZTA31Push SELECT * FROM ACE.dbo.ZTA31Push



USE [DIANA];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[ZTA31Pull] (
--[Id] bigint IDENTITY(1, 1) NOT NULL,
[Id] bigint NOT NULL,
[Sys_cd] varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
[Frm_id] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Wkset_id] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Ctrl_id] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Param_wkset] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Param_name] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Param_value] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Pid] bigint NULL,
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH ( PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE )
 ON [PRIMARY]
)
ON [PRIMARY];
GO
ALTER TABLE [dbo].[ZTA31Pull] SET (LOCK_ESCALATION = TABLE);
GO

select * into APIUAT01.DIANA.dbo.ZTA31Pull from ZTA31Pull
INSERT INTO APIUAT01.DIANA.dbo.ZTA31Pull SELECT * FROM ACE.dbo.ZTA31Pull


USE [DIANA];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[ZTA310] (
--[Id] bigint IDENTITY(1, 1) NOT NULL,
[Id] bigint NOT NULL,
[Sys_cd] varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
[Wkset_id] varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
[Wkset_ty] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Frm_id] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Ctrl_id] varchar(40) COLLATE Korean_Wansung_CI_AS NULL,
[Ctrl_ty] varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
[Field_ty] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Title] varchar(200) COLLATE Korean_Wansung_CI_AS NULL,
[TitleAlign] varchar(20) COLLATE Korean_Wansung_CI_AS NULL DEFAULT ('0'),
[TitleW] int NULL DEFAULT ((0)),
[Popup] varchar(40) COLLATE Korean_Wansung_CI_AS NULL,
[Txt] varchar(40) COLLATE Korean_Wansung_CI_AS NULL,
[TxtAlign] varchar(20) COLLATE Korean_Wansung_CI_AS NULL DEFAULT ('0'),
[Fix_chk] varchar(1) COLLATE Korean_Wansung_CI_AS NULL DEFAULT ((0)),
[Group_chk] varchar(1) COLLATE Korean_Wansung_CI_AS NULL DEFAULT ((0)),
[Show_chk] varchar(1) COLLATE Korean_Wansung_CI_AS NULL DEFAULT ((1)),
[Need_chk] varchar(1) COLLATE Korean_Wansung_CI_AS NULL DEFAULT ((0)),
[Edit_chk] varchar(1) COLLATE Korean_Wansung_CI_AS NULL DEFAULT ((1)),
[Band1] varchar(200) COLLATE Korean_Wansung_CI_AS NULL,
[Band2] varchar(200) COLLATE Korean_Wansung_CI_AS NULL,
[Sum_ty] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Format_ty] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Color_bg] varchar(40) COLLATE Korean_Wansung_CI_AS NULL,
[Color_fore] varchar(40) COLLATE Korean_Wansung_CI_AS NULL,
[Seq] int NULL,
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH ( PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE )
 ON [PRIMARY]
)
ON [PRIMARY];
GO
ALTER TABLE [dbo].[ZTA310] SET (LOCK_ESCALATION = TABLE);
GO

select * into APIUAT01.DIANA.dbo.ZTA310 from ZTA310
INSERT INTO APIUAT01.DIANA.dbo.ZTA310    SELECT * FROM ACE.dbo.ZTA310


USE [DIANA];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[ZTA300] (
--[Id] bigint IDENTITY(1, 1) NOT NULL,
[Id] bigint NOT NULL,
[Sys_cd] varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL,
[Frm_id] varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
[Ctrl_id] varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
[Ctrl_ty] varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
[CtrlW] int NULL DEFAULT ((0)),
[CtrlH] int NULL DEFAULT ((0)),
[Title] varchar(40) COLLATE Korean_Wansung_CI_AS NULL,
[TitleAlign] varchar(20) COLLATE Korean_Wansung_CI_AS NULL DEFAULT ((0)),
[Show_chk] char(1) COLLATE Korean_Wansung_CI_AS NULL DEFAULT ((0)),
[Edit_chk] char(1) COLLATE Korean_Wansung_CI_AS NULL DEFAULT ((0)),
[Wkset_id] varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
[Wkset_ty] varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH ( PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE )
 ON [PRIMARY]
)
ON [PRIMARY];
GO
ALTER TABLE [dbo].[ZTA300] SET (LOCK_ESCALATION = TABLE);
GO

select * into APIUAT01.DIANA.dbo.ZTA300 from ZTA300
INSERT INTO APIUAT01.DIANA.dbo.ZTA300    SELECT * FROM ACE.dbo.ZTA300


USE [DIANA];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[ZTA200] (
--[Id] bigint IDENTITY(1, 1) NOT NULL,
[Id] bigint NOT NULL,
[Sys_cd] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Frm_id] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Wkset_id] varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
[Wkset_ty] varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
[Wkset_nm] varchar(200) COLLATE Korean_Wansung_CI_AS NULL,
[New_chk] varchar(1) COLLATE Korean_Wansung_CI_AS NULL DEFAULT ((0)),
[Delete_chk] varchar(1) COLLATE Korean_Wansung_CI_AS NULL DEFAULT ((0)),
[Update_chk] varchar(1) COLLATE Korean_Wansung_CI_AS NULL DEFAULT ((0)),
[Use_chk] varchar(1) COLLATE Korean_Wansung_CI_AS NULL DEFAULT ((0)),
[Edit_chk] varchar(1) COLLATE Korean_Wansung_CI_AS NULL DEFAULT ((0)),
[ShowFooter_chk] varchar(1) COLLATE Korean_Wansung_CI_AS NULL DEFAULT ((0)),
[ShowGroupPanel_chk] varchar(1) COLLATE Korean_Wansung_CI_AS NULL DEFAULT ((0)),
[OptionsFind_chk] varchar(1) COLLATE Korean_Wansung_CI_AS NULL DEFAULT ((0)),
[ColumnAutoWidth_chk] varchar(1) COLLATE Korean_Wansung_CI_AS NULL DEFAULT ((0)),
[EvenRow_chk] varchar(1) COLLATE Korean_Wansung_CI_AS NULL DEFAULT ((0)),
[Memo] varchar(200) COLLATE Korean_Wansung_CI_AS NULL,
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH ( PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE )
 ON [PRIMARY]
)
ON [PRIMARY];
GO
ALTER TABLE [dbo].[ZTA200] SET (LOCK_ESCALATION = TABLE);
GO

select * into APIUAT01.DIANA.dbo.ZTA200 from ZTA200
INSERT INTO APIUAT01.DIANA.dbo.ZTA200    SELECT * FROM ACE.dbo.ZTA200


USE [DIANA];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[ZTA100] (
--[Id] bigint IDENTITY(1, 1) NOT NULL,
[Id] bigint NOT NULL,
[Sys_cd] varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL,
[Frm_id] varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
[Frm_nm] varchar(200) COLLATE Korean_Wansung_CI_AS NULL,
[Frm_ty] varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
[Hide_chk] varchar(1) COLLATE Korean_Wansung_CI_AS NULL,
[Use_chk] varchar(1) COLLATE Korean_Wansung_CI_AS NULL,
[Memo] varchar(200) COLLATE Korean_Wansung_CI_AS NULL,
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH ( PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE )
 ON [PRIMARY]
)
ON [PRIMARY];
GO
ALTER TABLE [dbo].[ZTA100] SET (LOCK_ESCALATION = TABLE);
GO

select * into APIUAT01.DIANA.dbo.ZTA100 from ZTA100
INSERT INTO APIUAT01.DIANA.dbo.ZTA100    SELECT * FROM ACE.dbo.ZTA100

USE [DIANA];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[ZTA50Pull] (
--[Id] bigint IDENTITY(1, 1) NOT NULL,
[Id] bigint NOT NULL,
[Sys_cd] varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
[Frm_id] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Wkset_id] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Ctrl_id] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Param_wkset] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Param_name] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Param_value] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
[Sql_id] varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH ( PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE )
 ON [PRIMARY]
)
ON [PRIMARY];
GO
ALTER TABLE [dbo].[ZTA50Pull] SET (LOCK_ESCALATION = TABLE);
GO

select * into APIUAT01.DIANA.dbo.ZTA50Pull from ZTA50Pull
INSERT INTO APIUAT01.DIANA.dbo.ZTA50Pull SELECT * FROM ACE.dbo.ZTA50Pull




